prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus
    build: .
    mem_limit: 128g
    environment:
      - CONSUL=consul
    links:
      - consul:consul
    ports:
      - "9090:9090"
    dns:
       - 127.0.0.1

consul:
    extends:
      file: docker-compose.yml
      service: consul
    ports:
      - "8500:8500"
